function preload() {
    configFile                = loadJSON('config.json')
    backgroundMusic           = loadSound('assets/sounds/soundtrack.mp3');
    imgOpeningScreen          = loadImage('assets/images/opening/home.png');
    imgExtraWitch             = loadImage('assets/images/opening/silhouette.png');
    fontOpeningScreen         = loadFont('assets/images/opening/font-hs.otf');
    imageScenario             = loadImage('assets/images/gameplay/scenario/florest.png');
    imgHipsta                 = loadImage('assets/images/gameplay/main/running.png');
    imgInvincibleHipsta       = loadImage('assets/images/gameplay/main/running-invincible.png');
    imgDashing                = loadImage('assets/images/gameplay/main/dashing.png');
    imgLifeIndicator          = loadImage('assets/images/gameplay/main/heart.png');
    transpImgLifeIndicator    = loadImage('assets/images/gameplay/main/heart-transparent.png');
    imgSpecialIndicator       = loadImage('assets/images/gameplay/main/broom.png');
    transpImgSpecialIndicator = loadImage('assets/images/gameplay/main/broom-transparent.png');
    imageDroplet              = loadImage('assets/images/gameplay/enemies/droplet.png');
    imageGhost                = loadImage('assets/images/gameplay/enemies/ghost.png');
    imageTroll                = loadImage('assets/images/gameplay/enemies/troll.png');
    imageFlyingDroplet        = loadImage('assets/images/gameplay/enemies/flying-droplet.png');
    jumpSoundEffect           = loadSound('assets/sounds/jump.mp3');
    gameOverImage             = loadImage('assets/images/gameplay/game-over.png');
}